services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./backend/.env.production
    ports:
      - "3030:3030"
    networks:
      - internal

  executor:
    build:
      context: ./executor
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./executor/.env.production
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - executor-tmp:/app/tmp
    networks:
      - internal

volumes:
  executor-tmp:

networks:
  internal:
